const CONFIG={entry:20,prize:500,upi:'shivaysharma52@ybl'};const KEY='saa_players';let data=JSON.parse(localStorage.getItem(KEY)||'[]');let adminLogged=false;
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='leaderboard')renderBoard();if(id==='admin'&&adminLogged)renderAdmin()}
document.getElementById('regForm').onsubmit=e=>{e.preventDefault();if(data.length>=48){regMsg.textContent='All 48 slots are full.';return}data.push({name:name.value,uid:uid.value,phone:phone.value,utr:utr.value,status:'Pending',kills:0,points:0});save();regMsg.textContent='Registration submitted. Admin verification pending.';e.target.reset()};
function renderBoard(){let p=[...data].sort((a,b)=>b.points-a.points||b.kills-a.kills);board.innerHTML=p.length?'<table><tr><th>#</th><th>Player</th><th>Kills</th><th>Points</th></tr>'+p.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${x.kills}</td><td>${x.points}</td></tr>`).join('')+'</table>':'<p class="muted">No players registered.</p>'}
function login(){/* Demo gate only. Production must use backend auth. */if(adminPassword.value!=='LOCAL_ADMIN_ONLY'){alert('For security, configure the real admin secret through the backend before deployment.');return}adminLogged=true;adminArea.hidden=false;renderAdmin()}
function renderAdmin(){players.innerHTML=data.map((x,i)=>`<div class="panel"><b>${esc(x.name)}</b><br>UID: ${esc(x.uid)}<br>UTR: ${esc(x.utr||'-')}<br>Status: ${x.status}<br><button onclick="approve(${i})">Approve</button> <button onclick="del(${i})">Delete</button></div>`).join('')||'<p class="muted">No players.</p>';scores.innerHTML=data.map((x,i)=>`<div class="panel"><b>${esc(x.name)}</b><input id="k${i}" type="number" value="${x.kills}"><input id="p${i}" type="number" value="${x.points}"><button class="primary" onclick="score(${i})">Save Score</button></div>`).join('')}
function approve(i){data[i].status='Approved';save();renderAdmin()}
function del(i){data.splice(i,1);save();renderAdmin();renderBoard()}
function score(i){data[i].kills=+document.getElementById('k'+i).value;data[i].points=+document.getElementById('p'+i).value;save();renderAdmin();renderBoard()}
function saveAdmin(){localStorage.setItem('saa_room',roomId.value);localStorage.setItem('saa_room_password',roomPassword.value);localStorage.setItem('saa_notice',announcement.value);notice.textContent=announcement.value;alert('Saved locally. Production version should store this on the backend.')}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
notice.textContent=localStorage.getItem('saa_notice')||'';renderBoard();